package:
  name: munkres
  version: !!str 1.0.7

source:
  fn: munkres-1.0.7.tar.gz
  url: https://pypi.python.org/packages/source/m/munkres/munkres-1.0.7.tar.gz
  md5: d534612326f7c7cadcfa61d109f96289

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - munkres


about:
  home: http://software.clapper.org/munkres/
  license:  BSD License
  summary: 'munkres algorithm for the Assignment Problem'
