package:
  name: svgwrite
  version: !!str 1.1.6

source:
  fn: svgwrite-1.1.6.tar.gz
  url: https://pypi.python.org/packages/source/s/svgwrite/svgwrite-1.1.6.tar.gz
  md5: 0d54ccf5584dd1f98fe22b7ac172bef1

requirements:
  build:
    - python
    - setuptools
    - pyparsing >=2.0.1

  run:
    - python
    - pyparsing >=2.0.1

test:
  imports:
    - svgwrite

about:
  home: http://bitbucket.org/mozman/svgwrite
  license: MIT License
  summary: 'A Python library to create SVG drawings.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
