package:
  name: cclib
  version: "1.5"

source:
  fn: cclib-1.5.post1.tar.gz
  url: https://github.com/cclib/cclib/releases/download/v1.5/cclib-1.5.post1.tar.gz
  md5: 1a50be48e4597b1a6dabe943da82a43c


requirements:
  build:
    - python

  run:
    - python
    - numpy

test:
  imports:
    - cclib
    - cclib.bridge
    - cclib.method
    - cclib.parser
    - cclib.progress

about:
  home: http://cclib.github.io/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'cclib: parsers and algorithms for computational chemistry'
