package:
  name: scripttest
  version: !!str 1.3

source:
  fn: scripttest-1.3.tar.gz
  url: https://pypi.python.org/packages/source/s/scripttest/scripttest-1.3.tar.gz
  md5: 1d1c5117ccfc7b5961cae6c1020c0848

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - scripttest

about:
  home: http://pythonpaste.org/scripttest/
  license: MIT License
