package:
  name: packmol
  version: "1!18.013"

source:
  fn: packmol.tar.gz
  url: https://github.com/mcubeg/packmol/archive/18.013.tar.gz

build:
  number: 0
  # no mingwpy support for py35 or py36 on win
  skip: True  # [win and py3k]

requirements:
  build:
    - zlib
    - python
    - mingwpy  [win]
    - gcc      [unix]
    - libgfortran [linux]
  run:
    - zlib
    - libgcc   [unix]
    - libgfortran [linux]

test:
  commands:
    - which packmol

about:
  home: http://www.ime.unicamp.br/~martinez/packmol/
  license: MIT
  summary: Packing Optimization for Molecular Dynamics Simulations
